"use client";

import { useRef, useState } from "react";
import { Loader2, Wand2 } from "lucide-react";
import { useResolvedAdmin } from "@/contexts/PublishedTenantProvider";
import { publicApiUrl } from "@/lib/publicEnv";
import { applyGeneratedPlan, type GeneratedPlanData } from "../utils/applyGeneratedPlan";
import SendPlannerDesignToAdminDialog from "../components/SendPlannerDesignToAdminDialog";
import { buildRoomPlannerEmailDesign } from "../utils/plannerDesignSnapshots";

type PlannerGenerateResponse = {
  data?: GeneratedPlanData;
  message?: string;
};

export default function AIPlannerForm() {
  const admin = useResolvedAdmin();
  const adminSlug = admin?.slug ?? "demo";
  const roomImageRef = useRef<HTMLInputElement>(null);
  const inspirationImageRef = useRef<HTMLInputElement>(null);
  const [text, setText] = useState("");
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [summary, setSummary] = useState<NonNullable<PlannerGenerateResponse["data"]> | null>(null);

  async function generatePlan() {
    const trimmed = text.trim();
    if (!trimmed || loading) return;

    setLoading(true);
    setError(null);

    const form = new FormData();
    form.set("admin_slug", adminSlug);
    form.set("text", trimmed);
    const roomFile = roomImageRef.current?.files?.[0];
    const inspirationFile = inspirationImageRef.current?.files?.[0];
    if (roomFile) form.set("room_image", roomFile);
    if (inspirationFile) form.set("inspiration_image", inspirationFile);

    try {
      const res = await fetch(`${publicApiUrl}/planner/generate`, {
        method: "POST",
        body: form,
      });
      const json = (await res.json()) as PlannerGenerateResponse;
      if (!res.ok || !json.data) {
        throw new Error(json.message || "Could not generate a planner result.");
      }

      applyGeneratedPlan(json.data);
      setSummary(json.data);
    } catch (e) {
      setError(e instanceof Error ? e.message : "Network error.");
    } finally {
      setLoading(false);
    }
  }

  return (
    <div className="planner-ai-form">
      <div className="planner-ai-form__header">
        <Wand2 className="h-5 w-5 text-fuchsia-600" />
        <div>
          <h2>AI Room Planner</h2>
          <p>Describe the furniture you need. The final layout is generated by planning rules.</p>
        </div>
      </div>

      <label className="planner-ai-form__field">
        <span>Your request</span>
        <textarea
          value={text}
          onChange={(e) => setText(e.target.value)}
          placeholder="Example: Plan a modern wardrobe for a 4m by 3m bedroom with oak finish and mixed shelves/hanging space."
          disabled={loading}
        />
      </label>

      <p className="planner-ai-form__hint">Upload a room photo or inspiration for better planning results</p>

      <label className="planner-ai-form__field">
        <span>Room photo (optional)</span>
        <input ref={roomImageRef} type="file" accept="image/jpeg,image/png,image/webp,image/gif" disabled={loading} />
      </label>

      <label className="planner-ai-form__field">
        <span>Inspiration image (optional)</span>
        <input
          ref={inspirationImageRef}
          type="file"
          accept="image/jpeg,image/png,image/webp,image/gif"
          disabled={loading}
        />
      </label>

      <button className="planner-ai-form__button" type="button" onClick={generatePlan} disabled={loading || !text.trim()}>
        {loading ? <Loader2 className="h-4 w-4 animate-spin" /> : null}
        Generate plan
      </button>

      {error && <div className="planner-ai-form__error">{error}</div>}

      {summary && (
        <div className="planner-ai-form__result">
          <h3>Generated result</h3>
          <p>Estimated price: {summary.estimated_price.toLocaleString()}</p>
          <p>Modules: {summary.modules.length}</p>
          {summary.warnings?.length ? <p>Notes: {summary.warnings.join(" · ")}</p> : null}
        </div>
      )}

      <div className="planner-ai-form__field" style={{ marginTop: 4 }}>
        <SendPlannerDesignToAdminDialog
          adminSlug={admin?.slug}
          plannerType="ai-room"
          plannerLabel="AI Room Planner"
          iconTrigger={false}
          className="planner-ai-form__button"
          buildDesign={() =>
            buildRoomPlannerEmailDesign(
              summary
                ? {
                    aiGeneratedPlan: {
                      request_id: summary.request_id,
                      intent: summary.intent,
                      estimated_price: summary.estimated_price,
                      furniture_plan: summary.furniture_plan,
                      modules: summary.modules,
                      warnings: summary.warnings,
                    },
                  }
                : undefined,
            )
          }
        />
      </div>
    </div>
  );
}
