"use client";

import { useRef, useState } from "react";
import { Loader2, Wand2 } from "lucide-react";
import { useResolvedAdmin } from "@/contexts/PublishedTenantProvider";
import { usePlannerStore } from "../store/usePlannerStore";
import type { PlannerCatalogItem } from "../types";
import { publicApiUrl } from "@/lib/publicEnv";

type GeneratedPlanItem = {
  id: string;
  name: string;
  category?: string;
  width_m: number;
  depth_m: number;
  height_m: number;
  color?: string;
  position?: { x?: number; z?: number };
  rotation_y?: number;
};

type PlannerGenerateResponse = {
  data?: {
    request_id: string;
    intent: Record<string, unknown>;
    furniture_plan: {
      room?: { width?: number; depth?: number; height?: number };
      items?: GeneratedPlanItem[];
    };
    modules: Record<string, unknown>[];
    estimated_price: number;
    warnings?: string[];
  };
  message?: string;
};

function applyGeneratedPlan(data: NonNullable<PlannerGenerateResponse["data"]>) {
  const store = usePlannerStore.getState();
  const room = data.furniture_plan.room;

  store.resetScene();
  if (room) {
    store.setRoom({
      ...usePlannerStore.getState().room,
      width: Number(room.width) || usePlannerStore.getState().room.width,
      depth: Number(room.depth) || usePlannerStore.getState().room.depth,
      height: Number(room.height) || usePlannerStore.getState().room.height,
    });
  }

  const catalogItems: PlannerCatalogItem[] = (data.furniture_plan.items ?? []).map((item) => ({
    id: `planner-${data.request_id}-${item.id}`,
    name: item.name,
    category: item.category || "Generated plan",
    vendor: "",
    price: 0,
    width: Number(item.width_m) || 0.8,
    depth: Number(item.depth_m) || 0.6,
    height: Number(item.height_m) || 0.8,
    color: item.color || "#BFA58A",
  }));

  store.addEphemeralCatalogItems(catalogItems);

  for (const [index, catalogItem] of catalogItems.entries()) {
    store.addItem(catalogItem.id);
    const source = data.furniture_plan.items?.[index];
    const placed = usePlannerStore.getState().placedItems.at(-1);
    if (placed && source?.position) {
      usePlannerStore
        .getState()
        .updateItemPosition(placed.id, Number(source.position.x) || 0, Number(source.position.z) || 0);
    }
  }
}

export default function AIPlannerForm() {
  const admin = useResolvedAdmin();
  const adminSlug = admin?.slug ?? "demo";
  const roomImageRef = useRef<HTMLInputElement>(null);
  const inspirationImageRef = useRef<HTMLInputElement>(null);
  const [text, setText] = useState("");
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [summary, setSummary] = useState<NonNullable<PlannerGenerateResponse["data"]> | null>(null);

  async function generatePlan() {
    const trimmed = text.trim();
    if (!trimmed || loading) return;

    setLoading(true);
    setError(null);

    const form = new FormData();
    form.set("admin_slug", adminSlug);
    form.set("text", trimmed);
    const roomFile = roomImageRef.current?.files?.[0];
    const inspirationFile = inspirationImageRef.current?.files?.[0];
    if (roomFile) form.set("room_image", roomFile);
    if (inspirationFile) form.set("inspiration_image", inspirationFile);

    try {
      const res = await fetch(`${publicApiUrl}/planner/generate`, {
        method: "POST",
        body: form,
      });
      const json = (await res.json()) as PlannerGenerateResponse;
      if (!res.ok || !json.data) {
        throw new Error(json.message || "Could not generate a planner result.");
      }

      applyGeneratedPlan(json.data);
      setSummary(json.data);
    } catch (e) {
      setError(e instanceof Error ? e.message : "Network error.");
    } finally {
      setLoading(false);
    }
  }

  return (
    <div className="planner-ai-form">
      <div className="planner-ai-form__header">
        <Wand2 className="h-5 w-5 text-fuchsia-600" />
        <div>
          <h2>AI Room Planner</h2>
          <p>Describe the furniture you need. The final layout is generated by planning rules.</p>
        </div>
      </div>

      <label className="planner-ai-form__field">
        <span>Your request</span>
        <textarea
          value={text}
          onChange={(e) => setText(e.target.value)}
          placeholder="Example: Plan a modern wardrobe for a 4m by 3m bedroom with oak finish and mixed shelves/hanging space."
          disabled={loading}
        />
      </label>

      <p className="planner-ai-form__hint">Upload a room photo or inspiration for better planning results</p>

      <label className="planner-ai-form__field">
        <span>Room photo (optional)</span>
        <input ref={roomImageRef} type="file" accept="image/jpeg,image/png,image/webp,image/gif" disabled={loading} />
      </label>

      <label className="planner-ai-form__field">
        <span>Inspiration image (optional)</span>
        <input
          ref={inspirationImageRef}
          type="file"
          accept="image/jpeg,image/png,image/webp,image/gif"
          disabled={loading}
        />
      </label>

      <button className="planner-ai-form__button" type="button" onClick={generatePlan} disabled={loading || !text.trim()}>
        {loading ? <Loader2 className="h-4 w-4 animate-spin" /> : null}
        Generate plan
      </button>

      {error && <div className="planner-ai-form__error">{error}</div>}

      {summary && (
        <div className="planner-ai-form__result">
          <h3>Generated result</h3>
          <p>Estimated price: {summary.estimated_price.toLocaleString()}</p>
          <p>Modules: {summary.modules.length}</p>
          {summary.warnings?.length ? <p>Notes: {summary.warnings.join(" · ")}</p> : null}
        </div>
      )}
    </div>
  );
}
